#
# Compile options:
#
# Set -DSYSV if on System V
# Set -DNEW_CTIME if using the table-driven version of ctime (i.e., if
#   your struct tm contains a tm_zone field)
# Set -DBIGFONT= and -DSMALLFONT= whatever fonts you like
# Pick -O or -g
#

CFLAGS=-DBIGFONT=\"9x15\" -DSMALLFONT=\"6x10\" -g

OFILES=sunclock.o bitmaps.o astro.o

sunclock: $(OFILES)
	cc $(CFLAGS) $(OFILES) -o $@ -lX11 -lm
